__author__ = 'Jesse Laptop'

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# Answer 4613732

limit = 4000000

a = 1
b = 1
x = 0
answer = 0

while True:
	x = a + b  # Calculate sequence (1 + 1 = 2) ... (1 + 2 = 3) ... ...
	if str(x / 2).split(".")[1] == "0":  # Checks if even
		answer += x  # If even, add to running total
	a = b  # Shift forward 1 (1 + _ = _)
	b = x  # Moved answer to slot 1 (1 + 2 = _)
	if x > limit:  # Stop at limit
		break

print("Answer")
print(answer)