__author__ = 'Jesse Laptop'

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

limit = 100

a = 1
b = 1
x = 0
numList = []
numList.append(1)
print("A\t\tB\t\tX")
print()
for i in range(limit):
	x = a + b
	print(str(a) + "\t\t" + str(b) + "\t\t" + str(x))
	numList.append(x)
	a = b
	b = x
	if x > limit: break

print(numList)